class StringRes {
  static const travelTheWorld = 'Travel The World';
  static const letTravel = "Let's Travel";
  static const enjoyFood = 'Enjoy Food';
  static const continues = 'Continue';
  static const india = 'India';
  static const newzealand = 'Newzealand';
  static const newzealandhotel = 'Queenstown';
  static const indonesia = 'Indonesia';
  static const indonesiahotel = ' JIMBARAN BAY';
  static const canada = 'Canada';
  static const japan = 'Japan';
  static const singapor = 'Singapor';
  static const london = 'London';
  static const dubai = 'Dubai';
  static const price = "\$500";
  static const book = "BookNow";
  static const details = "Detail";
  static const hotel = " Hotel";
  static const hintname = "EnterName";
  static const labelname = "EnterName";
  static const hintnumber = "EnterNumber";
  static const labelnumber = "EnterNumber";
  static const hintemail = "EnterValidEmail";
  static const labelemail = "EnterValidEmail";
  static const hintcity = "EnterCity";
  static const labelcity = "EnterCity";
  static const appname = "RoyelHotel";
}
